services:
  backend:
    build: ./backend
    ports:
      - 4005:4000
    volumes:
      - ./backend/src:/app/src
      - ./backend/demo.sqlite:/app/demo.sqlite
    env_file:
      - ./global.env
      - ./backend/.env
      - ./secret.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://backend:4000/graphql?query=%7B__typename%7D -H 'Apollo-Require-Preflight: true' || exit 1",
        ]
      interval: 10s
      timeout: 30s
      retries: 5
  frontend:
    build: ./frontend
    # command: "sh -c ./start.sh"
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./global.env
      - ./secret.env
    depends_on:
      backend:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
